version: '3'
services:
  my-express-load-balancer-container-1:
    build:
      context: .
    ports:
      - "3001:3000"
    environment:
      - NAME=app1

  my-express-load-balancer-container-2:
    build:
      context: .
    ports:
      - "3002:3000"
    environment:
      - NAME=app2

  nginx-load-balancer:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "3000:80"